services:
  - type: web
    name: your-service-name
    env: python
    runtime: python-3.12.0
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "your-start-command"