services:
  - type: web
    name: your-service-name
    env: python
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "your-start-command"
    pythonVersion: 3.12.3